### ISSUE TITLE
Provide CLI installation instructions

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala-eclipse#1]
Ideally I just have to clone your repo, paste in a command and then start up eclipse and it works, right? Can you do that?

**Comment by nishant-mor** [comment]
@sils1297 
Actually you don't need the complete repository, just the jar file in the jar folder. 

Once the plugin is complete we can publish it to eclipse marketplace.
Then it would we a lot easier to install plugin.
https://marketplace.eclipse.org/quickstart
![capture](https://cloud.githubusercontent.com/assets/11739327/13891039/cd060e0c-ed74-11e5-9636-e132b10034bb.PNG)

**Comment by nishant-mor** [comment]
We can do that CLI part only if eclipse path is there in the environment variables.
then use copy command to copy this jar into $eclipse_home/plugins folder

**Comment by nishant-mor** [comment]
@sils1297 I have updated the Readme to add a new method for plugin installation within Eclipse which i think will be better for user compared to manually copying some file.

**Comment by sils1297** [comment]
neat :)
