### ISSUE TITLE
handle case where coala isn't installed

### ISSUE THREAD

**Issue by arafsheikh** [coala-analyzer/coala-eclipse#13]

**Comment by harshdattani** [comment]
How are we going forward on this?

**Comment by arafsheikh** [comment]
I haven't given it a lot of thought but we can check if the coala binary is present on startup and if not then show a message to install it.

**Comment by harshdattani** [comment]
Can you check if we can check coala installation just while installing eclipse plugin? 
@sils1297 Any inputs on this?

**Comment by sils1297** [comment]
possibly even on every run

**Comment by Makman2** [comment]
if invocation fails -> coala does not exist
if invocations succeeds -> coala exists

I think there's no need to make heavy special checks, just catch the case when coala isn't invocable and report a nice message :+1:

**Comment by harshdattani** [comment]
@Makman2 yes!
