### ISSUE TITLE
License

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala-eclipse#2]
Hey, can we license this AGPL?

**Comment by nishant-mor** [comment]
Yeah sure.

**Comment by sils1297** [comment]
@arafsheikh can you add a license?

**Comment by arafsheikh** [comment]
@sils1297 AGPL?

**Comment by sils1297** [comment]
yes

Sincerely,

Lasse Schuirmann

lasse@schuirmann.net
http://coala-analyzer.org/ - http://viperdev.io/ - http://gitmate.com/
