### ISSUE TITLE
binaries in repo

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala-eclipse#5]
We seem to have a binary (jar) file at https://github.com/coala-analyzer/coala-eclipse/tree/master/jar
Do we want this ? I think we should probably put it in travis/circle artifacts and link that if users want to download the jar directly

**Comment by Makman2** [comment]
Indeed that's way better :+1:

**Comment by smsubham** [comment]
How can i contribute here and get added ?

**Comment by sils1297** [comment]
Hey @smsubham are you at PyCon? If so, come by Portland Ballroom 253 :)

**Comment by sils1297** [comment]
I have sent you an invitation to join our community. This is needed so we can coordinate tasks with you and make sure no two persons are working on the same thing. If you can't find the mail, you should be able to join us at http://github.com/coala-analyzer/!

We'd love to be able to help you when problems occur. Just join us on [our gitter channel](https://gitter.im/coala-analyzer/coala) and tell us about them :)

**Comment by smsubham** [comment]
joined @sils1297 thanks

**Comment by Makman2** [comment]
uhm this issue isn't solved :O

**Comment by Makman2** [comment]
oh it has vanished, @arafsheikh please write next time why you close an issue if there's no commit reference :+1:

**Comment by arafsheikh** [comment]
Sorry.. :)
