### ISSUE TITLE
Static code analysis

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala-eclipse#6]
Probably we want CheckStyleBear to run on the code :) ?

**Comment by Makman2** [comment]
You mean as a default? sounds good^^

**Comment by AbdealiJK** [comment]
Actually I meant CheckstyleBear to run on the code in this repo. I.e. Lint the code in this repo for style issues

**Comment by Makman2** [comment]
ahhh okay, yeah that's good too :3

**Comment by arafsheikh** [comment]
Should I add Gitmate to this repo?

**Comment by sils1297** [comment]
as you like, you're maintainer

Sincerely,

Lasse Schuirmann

lasse@schuirmann.net
http://coala-analyzer.org/ - http://viperdev.io/ - http://gitmate.com/

**Comment by Makman2** [comment]
@arafsheikh Is it added?

**Comment by arafsheikh** [comment]
Yup

**Comment by harshdattani** [comment]
Perfect
